import Head from 'next/head';
import React, { ReactNode } from 'react';
import Navbar from './Navbar';

interface LayoutProps {
  title: string;
  children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ title, children }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="bg-gray-300">{children}</div>
    </div>
  );
};

export default Layout;
